### PR TITLE
Pre-GRC Tuning

### LINKED ISSUE #5: Drive Configs are Wrong
- There is no NavXIO abstraction so currently the pigeon one is being used (we don't have a pigeon). You can find another team who uses Advantage Kit with a NavX and use their abstraction or make your own
- The Spark Max abstractions are used instead of the Talon ones in the robot container switch statement. We have [krakens](https://wcproducts.com/products/kraken) controlled via TalonFX motor controllers. Additionally, the configs for TalonFX are set for L2 swerve when we use L3+, look at this year's 2024-Robot repo for the correct gear ratios.
- The ModuleIOSim used for simulating the robot likely does not have the correct values (gearing, MOI, motor, etc). I recommend looking for another team with L3+ Kraken Swerve who also uses Advantage Kit and take their configs

### PR DESCRIPTION
**Pull request by GreenTomato5**
Adds CAN IDs taken from last years configs for each module in constants. These should be CHECKED PLEASE because the IDs may be mixed up and likley are. This is because we didn't properly name our modules last year when using YAGSL so "Front left" in configs wasn't actually front left. But the wheels should still move. I also added the NavX IO abstraction which currently uses the MXP port. This may need to be adjusted to use USB C but for now it should be fine.

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/drive/GyroIONavx2.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
+package frc.robot.subsystems.drive;
+
+import com.kauailabs.navx.frc.AHRS;
```
Comment (PotmanNob) [inline src/main/java/frc/robot/subsystems/drive/GyroIONavx2.java:3]: Looks fine, but could you post the link to download the NavX library since I don't think i have it yet

File: src/main/java/frc/robot/Constants.java [hunk 2]
```diff
@@ -269,26 +278,33 @@ public static final class Hybrid {
...
-				public static final int DRIVE0_ID = 0;
-				public static final int TURN0_ID = 1;
-				public static final int CANCODER0_ID = 2;
-				public static final double OFFSET0 = 0.0;
+				// CAN/Device IDS and offsets (May be Wrong, guessed which ids are correct off vibes)
+
+				// TODO: Confirm module IDs are associated with correct module and tune module offsets if last years dont work
+
+				// Front Left Module
+				public static final int DRIVE0_ID = 8;
```
Comment (PotmanNob) [inline src/main/java/frc/robot/Constants.java]: I don't have access to the robot until recruitment week, so I can't double check CAN ids. You should check again just in case or get someone else there to do it for you.

**Review by PotmanNob — APPROVED** [review]
Looks good, just double check the CAN ids just in case.

File: src/main/java/frc/robot/subsystems/drive/GyroIONavx2.java (hunk 1 above)
Comment (GreenTomato5) [reply src/main/java/frc/robot/subsystems/drive/GyroIONavx2.java:3]: Here: 
    https://dev.studica.com/releases/2024/NavX.json
    The vendor dep json thing should be in the branch so you don't have to re-install it

**Comment by GreenTomato5** [comment]
Problem is bc talons and sparks are using a different odo thread and the talons use blocking (so they wait for motor controller to report data and that adds latency so the data collected isnt aligned with the timestamps of the spark data collected) and the sparks use polling (just ask the sparks for data). Idk how to effectivley mix the two sampling types so the odo data works and it would probably take a lot of time so I'm gona switch it to the non advanced swerve template so we can get to testing important stuff faster

**Comment by GreenTomato5** [comment]
I lied, made a mixed thread so should maybe work

**Comment by GreenTomato5** [comment]
Todo (After sept 9, putting this here so we don't forget):
- Fix absolute encoder offsets, idk why they weren't offsetting
- Add back sys id and test it for drive controller values (once we get ground) 
- PID tune (and probably change the setpoints) of intake, amp bar, and shooter states
- Write climbers
- Automatic state transitions based on at setpoint, timers, and current sensing
- Add beam breaks or sumth
